apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: testssl-
build:
  artifacts:
    - image: tickr-client
      context: nossl
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/config.yaml
