apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: tickr
build:
  artifacts:
    - image: tickr/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/dev/auth.yaml
    - infra/dev/auth-db.yaml
    - infra/dev/ingress.yaml
